import { makeStyles, shorthands } from "@fluentui/react-components";

const cardShadow = "0 0 2px var(--cp-border), 0 1px 2px var(--cp-border)";

export const useStyles = makeStyles({
  root: { minHeight: "100vh", backgroundColor: "var(--cp-bg)", color: "var(--cp-text)" },
  shell: { display: "grid", gridTemplateColumns: "208px minmax(0, 1fr)", minHeight: "100vh", "@media (min-width: 861px) and (max-width: 1199px)": { gridTemplateColumns: "72px minmax(0, 1fr)" }, "@media (max-width: 860px)": { gridTemplateColumns: "minmax(0, 1fr)", gridTemplateRows: "auto 1fr" } },
  sidebar: { position: "sticky", top: 0, height: "100vh", minWidth: 0, backgroundColor: "var(--cp-bg-elevated)", ...shorthands.borderRight("1px", "solid", "var(--cp-border)"), padding: "24px 12px 20px", boxSizing: "border-box", display: "flex", flexDirection: "column", "@media (min-width: 861px) and (max-width: 1199px)": { padding: "24px 8px 20px" }, "@media (max-width: 860px)": { position: "relative", height: "auto", padding: "10px 12px", ...shorthands.borderRight("0") } },
  brand: { color: "var(--cp-text)", fontSize: "20px", fontWeight: 720, letterSpacing: "-0.025em" },
  tagline: { color: "var(--cp-text-soft)", fontSize: "12px", lineHeight: 1.55, margin: "12px 0 28px", maxWidth: "180px", "@media (max-width: 860px)": { display: "none" } },
  navGroup: { color: "var(--cp-text-soft)", fontSize: "11px", fontWeight: 700, letterSpacing: "0.1em", margin: "20px 10px 7px", textTransform: "uppercase", "@media (max-width: 860px)": { display: "none" } },
  nav: { display: "flex", flexDirection: "column", gap: "3px", "@media (max-width: 860px)": { flexDirection: "row", flexWrap: "nowrap", overflowX: "auto", paddingBottom: "2px" } },
  navLink: { color: "var(--cp-text-muted)", backgroundColor: "transparent", textDecorationLine: "none", padding: "10px 11px", borderRadius: "10px", display: "flex", gap: "10px", alignItems: "center", minHeight: "20px", transitionProperty: "background-color,color", transitionDuration: "120ms", ":hover": { backgroundColor: "var(--cp-surface-soft)", color: "var(--cp-text)" }, ":focus-visible": { outline: "3px solid var(--cp-accent)", outlineOffset: "2px" }, "@media (max-width: 860px)": { flex: "0 0 auto", padding: "8px 10px", fontSize: "13px" } },
  navActive: { backgroundColor: "var(--cp-accent-soft)", color: "var(--cp-accent)", fontWeight: 650 },
  main: { padding: "24px 24px 72px", width: "100%", minWidth: 0, boxSizing: "border-box", overflowWrap: "anywhere", "@media (min-width: 1600px)": { padding: "28px 40px 72px" }, "@media (max-width: 860px)": { padding: "20px 20px calc(100px + env(safe-area-inset-bottom))" }, "@media (max-width: 480px)": { padding: "16px 16px calc(100px + env(safe-area-inset-bottom))" } },
  eyebrow: { color: "var(--cp-accent)", fontSize: "12px", fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase" },
  header: { display: "flex", flexWrap: "wrap", justifyContent: "space-between", alignItems: "flex-end", gap: "20px", marginBottom: "28px", paddingBottom: "24px", ...shorthands.borderBottom("1px", "solid", "var(--cp-border)") },
  title: { fontSize: "clamp(30px, 4vw, 46px)", fontWeight: 740, letterSpacing: "-0.05em", margin: "6px 0 9px", lineHeight: 1.05 },
  subtitle: { color: "var(--cp-text-muted)", maxWidth: "780px", lineHeight: 1.7, fontSize: "15px" },
  statusStrip: { display: "flex", alignItems: "center", gap: "10px", flexWrap: "wrap", minHeight: "34px", backgroundColor: "var(--cp-surface-soft)", ...shorthands.border("1px", "solid", "var(--cp-border)"), borderRadius: "10px", padding: "7px 12px", marginBottom: "24px", color: "var(--cp-text-muted)", fontSize: "12px" },
  toolbar: { display: "grid", gridTemplateColumns: "minmax(190px, 1.6fr) repeat(3, minmax(128px, .8fr)) auto", gap: "12px", alignItems: "end", margin: "20px 0 18px", padding: "16px", backgroundColor: "var(--cp-bg-elevated)", ...shorthands.border("1px", "solid", "var(--cp-border)"), borderRadius: "16px", "@media (max-width: 1150px)": { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" }, "@media (max-width: 560px)": { gridTemplateColumns: "repeat(2, minmax(0, 1fr))", padding: "12px", "& > :first-child": { gridColumn: "1 / -1" } } },
  compactToolbar: { display: "flex", flexWrap: "wrap", gap: "10px", alignItems: "end", margin: "18px 0 20px" },
  filterControl: { minWidth: 0, "& .fui-Select": { minWidth: 0, width: "100%", boxSizing: "border-box" }, "& .fui-Input": { minWidth: 0, width: "100%", boxSizing: "border-box" } },
  filterCheck: { minHeight: "40px", display: "flex", alignItems: "center", paddingBottom: "1px" },
  filterButton: { minHeight: "40px", whiteSpace: "nowrap" },
  radarToolbar: { display: "flex", flexWrap: "wrap", gap: "12px", alignItems: "end", margin: "20px 0 18px", padding: "16px", backgroundColor: "var(--cp-bg-elevated)", ...shorthands.border("1px", "solid", "var(--cp-border)"), borderRadius: "16px", "@media (max-width: 560px)": { padding: "12px" } },
  radarSearch: { flexGrow: 1.7, flexShrink: 1, flexBasis: "240px" },
  radarFilter: { flexGrow: 1, flexShrink: 1, flexBasis: "148px" },
  radarToolbarFooter: { display: "flex", flexBasis: "100%", minWidth: 0, gap: "12px", alignItems: "center", justifyContent: "space-between" },
  grid: { display: "grid", gap: "16px" },
  card: { minWidth: 0, backgroundColor: "var(--cp-surface)", ...shorthands.border("1px", "solid", "var(--cp-border)"), borderRadius: "16px", padding: "20px", boxShadow: cardShadow, transitionProperty: "border-color,background-color", transitionDuration: "120ms", ":hover": { ...shorthands.border("1px", "solid", "var(--cp-border-strong)") }, ":focus-within": { ...shorthands.border("1px", "solid", "var(--cp-accent)") }, "@media (max-width: 480px)": { padding: "16px" } },
  cardSelected: { backgroundColor: "var(--cp-accent-soft)", ...shorthands.border("1px", "solid", "var(--cp-accent)") },
  cardTop: { display: "flex", justifyContent: "space-between", gap: "16px", alignItems: "flex-start" },
  eventTitle: { margin: "9px 0 10px", fontSize: "22px", lineHeight: 1.34, letterSpacing: "-0.025em" },
  articleTitleButton: { color: "var(--cp-text)", backgroundColor: "inherit", padding: 0, margin: 0, ...shorthands.border("0"), fontFamily: "inherit", fontSize: "inherit", fontWeight: "inherit", lineHeight: "inherit", textAlign: "left", cursor: "pointer", ":hover": { color: "var(--cp-accent)", textDecorationLine: "underline" }, ":focus-visible": { outline: "3px solid var(--cp-accent)", outlineOffset: "4px", borderRadius: "2px" } },
  articleMeta: { display: "flex", flexWrap: "wrap", gap: "7px", alignItems: "center", color: "var(--cp-text-muted)", fontSize: "12px" },
  articleDates: { display: "flex", flexWrap: "wrap", gap: "4px 16px", fontSize: "12px", color: "var(--cp-text-soft)", marginBottom: "16px", lineHeight: 1.6 },
  editionMeta: { display: "flex", flexWrap: "wrap", gap: "12px", alignItems: "center", padding: "12px 0", marginBottom: "12px", ...shorthands.borderBottom("1px", "solid", "var(--cp-border)"), color: "var(--cp-text-muted)" },
  excerptDisclosure: { color: "var(--cp-text-muted)", lineHeight: 1.75, "& > summary": { listStyleType: "none", cursor: "pointer" }, "&[open] > summary > span:first-child": { display: "none" }, "& > summary:focus-visible": { outline: "2px solid var(--cp-accent)", outlineOffset: "4px" } },
  excerptToggle: { display: "block", fontSize: "12px", color: "var(--cp-accent)", marginTop: "8px" },
  summary: { color: "var(--cp-text)", fontSize: "16px", lineHeight: 1.8, margin: 0, whiteSpace: "pre-wrap", overflowWrap: "anywhere", maxWidth: "76ch" },
  summaryLabel: { color: "var(--cp-text-muted)", fontSize: "12px", fontWeight: 600, marginBottom: "8px" },
  score: { color: "var(--cp-text-muted)", fontSize: "12px", flexShrink: 0, whiteSpace: "nowrap", paddingTop: "4px" },
  meta: { display: "flex", flexWrap: "wrap", gap: "8px", alignItems: "center", marginTop: "14px", color: "var(--cp-text-muted)" },
  reason: { marginTop: "16px", padding: "10px 12px", backgroundColor: "var(--cp-surface-soft)", ...shorthands.borderLeft("3px", "solid", "var(--cp-accent)"), borderRadius: "0 10px 10px 0", color: "var(--cp-text-muted)", fontSize: "13px", lineHeight: 1.6 },
  actions: { display: "flex", flexWrap: "wrap", justifyContent: "space-between", alignItems: "center", marginTop: "16px", gap: "12px" },
  stats: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: "12px", marginBottom: "20px" },
  stat: { backgroundColor: "var(--cp-surface)", color: "var(--cp-text)", padding: "16px", borderRadius: "16px", ...shorthands.border("1px", "solid", "var(--cp-border)") },
  statValue: { fontSize: "26px", fontWeight: 700 }, statLabel: { color: "var(--cp-text-muted)", fontSize: "12px", marginTop: "4px" },
  sourceRow: { display: "grid", gridTemplateColumns: "minmax(180px, 1.3fr) 1fr 1fr 90px", gap: "16px", alignItems: "center", padding: "14px 0", ...shorthands.borderBottom("1px", "solid", "var(--cp-border)"), "@media (max-width: 760px)": { gridTemplateColumns: "1fr" } },
  detailGrid: { display: "grid", gridTemplateColumns: "minmax(0, 1.55fr) minmax(250px, .65fr)", gap: "16px", "@media (max-width: 850px)": { gridTemplateColumns: "1fr" } },
  evidence: { padding: "14px 0", ...shorthands.borderBottom("1px", "solid", "var(--cp-border)") },
  empty: { textAlign: "center", padding: "56px 20px", color: "var(--cp-text-muted)", backgroundColor: "var(--cp-surface)", borderRadius: "16px", ...shorthands.border("1px", "dashed", "var(--cp-border-strong)") },
  buttonGroup: { display: "flex", gap: "8px", flexWrap: "wrap", alignItems: "center", marginTop: "8px" },
  eventActions: { display: "flex", flexDirection: "column", minWidth: 0 },
  eventActionButtons: { display: "flex", flexWrap: "wrap", alignItems: "stretch", gap: "8px", marginTop: 0, "& > button": { minHeight: "32px" } },
  notice: { backgroundColor: "var(--cp-surface-soft)", color: "var(--cp-text-muted)", ...shorthands.border("1px", "solid", "var(--cp-border)"), borderRadius: "10px", padding: "12px", marginBottom: "16px", lineHeight: 1.6 },
  error: { backgroundColor: "var(--cp-accent-soft)", color: "var(--cp-text)", ...shorthands.border("1px", "solid", "var(--cp-danger)"), padding: "12px", borderRadius: "10px", margin: "12px 0", display: "grid", gap: "8px", justifyItems: "start", lineHeight: 1.5, overflowWrap: "anywhere" },
  field: { minWidth: 0 }, formGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 230px), 1fr))", gap: "16px" },
  sourceHeading: { margin: "0 0 6px" }, jobList: { listStyleType: "none", padding: 0, margin: 0 },
  skipLink: { position: "absolute", left: "12px", top: "-80px", zIndex: 10, backgroundColor: "var(--cp-surface)", color: "var(--cp-text)", padding: "12px", ":focus": { top: "12px" } },
  disclosure: { marginTop: "16px", color: "var(--cp-text-muted)" },
  muted: { color: "var(--cp-text-muted)" },
  listSurface: { backgroundColor: "var(--cp-surface)", borderRadius: "16px", ...shorthands.border("1px","solid","var(--cp-border)"), overflow: "hidden", boxShadow: cardShadow },
  newsRow: { display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:"14px",padding:"15px 16px",...shorthands.borderBottom("1px","solid","var(--cp-border)"), ...shorthands.borderLeft("3px", "solid", "var(--cp-surface)"), transitionProperty: "background-color,border-color", transitionDuration: "120ms", ":hover": { backgroundColor: "var(--cp-surface-soft)", ...shorthands.borderLeft("3px", "solid", "var(--cp-border-strong)") }, ":focus-within": { backgroundColor: "var(--cp-accent-soft)", ...shorthands.borderLeft("3px", "solid", "var(--cp-accent)") }, "@media (max-width: 560px)":{gridTemplateColumns:"1fr",gap:"6px",padding:"14px"} },
  newsRowSelected: { backgroundColor: "var(--cp-accent-soft)", ...shorthands.borderLeft("3px", "solid", "var(--cp-accent)") },
  rowContent: {minWidth:0},
  rowTitle: {fontSize:"17px",fontWeight:650,lineHeight:1.38,margin:"6px 0"},
  rowPreview: {margin:0,color:"var(--cp-text-muted)",fontSize:"13px",lineHeight:1.55,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"},
  rowActions: {display:"flex",alignItems:"center",gap:"4px",flexWrap:"wrap","@media (min-width: 561px)":{maxWidth:"188px",justifyContent:"flex-end"}},
  feedWithPreview: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) minmax(360px, .9fr)", gap: "20px", alignItems: "start", "@media (max-width: 980px)": { gridTemplateColumns: "minmax(0, 1fr)" } },
  previewSlot: { position: "sticky", top: "20px", maxHeight: "calc(100vh - 40px)", overflowY: "auto", "@media (max-width: 980px)": { position: "static", maxHeight: "none", overflowY: "visible" } },
  topicShell: { backgroundColor: "var(--cp-surface)", borderRadius: "16px", ...shorthands.border("1px", "solid", "var(--cp-border)"), boxShadow: cardShadow, overflow: "hidden" },
  topicIntro: { padding: "18px 20px 0" },
  topicLayout: { display: "grid", gridTemplateColumns: "minmax(0, 1.25fr) minmax(310px, .75fr)", alignItems: "start", "@media (max-width: 900px)": { gridTemplateColumns: "minmax(0, 1fr)" } },
  topicMapPanel: { minWidth: 0, padding: "8px 12px 18px", ...shorthands.borderRight("1px", "solid", "var(--cp-border)"), "@media (max-width: 900px)": { ...shorthands.borderRight("0"), ...shorthands.borderBottom("1px", "solid", "var(--cp-border)") } },
  topicMap: { display:"block",width:"100%",height:"auto",minHeight:"380px", "@media (max-width: 560px)": { minHeight: "320px" } },
  mapEdge: { stroke: "var(--cp-border-strong)", opacity: 0.7, transitionProperty: "opacity,stroke-width", transitionDuration: "160ms" },
  mapEdgeMuted: { opacity: 0.22 },
  mapNode: {cursor:"pointer",outlineStyle:"none","&:focus-visible circle":{stroke:"var(--cp-accent)",strokeWidth:"4px"},"&:hover circle":{fill:"var(--cp-accent-soft)"}},
  mapNodeSelected: { "& circle": { fill: "var(--cp-accent-soft)", stroke: "var(--cp-accent)", strokeWidth: "3px" } },
  topicLabel: { fill: "var(--cp-text)", fontSize: "14px", fontWeight: 650, pointerEvents: "none" },
  topicCount: { fill: "var(--cp-text-muted)", fontSize: "11px", pointerEvents: "none" },
  topicResults: { minWidth: 0, padding: "18px", backgroundColor: "var(--cp-bg-elevated)" },
  topicResultsHeader: { display: "flex", gap: "12px", alignItems: "baseline", justifyContent: "space-between", marginBottom: "12px" },
  topicResultList: { display: "grid", gap: "6px", maxHeight: "390px", overflowY: "auto" },
  topicResult: { width: "100%", fontFamily: "inherit", fontSize: "inherit", textAlign: "left", color: "var(--cp-text)", backgroundColor: "var(--cp-surface)", ...shorthands.border("1px", "solid", "var(--cp-border)"), borderRadius: "10px", padding: "12px", cursor: "pointer", ":hover": { ...shorthands.border("1px", "solid", "var(--cp-border-strong)") }, ":focus-visible": { outline: "3px solid var(--cp-accent)", outlineOffset: "2px" } },
  topicResultSelected: { backgroundColor: "var(--cp-accent-soft)", ...shorthands.border("1px", "solid", "var(--cp-accent)") },
  topicResultTitle: { display: "block", lineHeight: 1.4, fontSize: "14px", fontWeight: 650 },
  topicResultMeta: { display: "block", marginTop: "6px", color: "var(--cp-text-muted)", fontSize: "12px" },
  topicPreview: { marginTop: "16px" },
  sectionHeader: { display: "flex", justifyContent: "space-between", gap: "12px", alignItems: "baseline", margin: "4px 0 12px" },
  watchlist: { backgroundColor: "var(--cp-bg-elevated)", ...shorthands.border("1px", "solid", "var(--cp-border)"), borderRadius: "16px", padding: "18px 20px" },
  watchlistCount: { flexShrink: 0, whiteSpace: "nowrap" },
  watchlistItem: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) auto", gap: "12px", padding: "12px 0", ...shorthands.borderBottom("1px", "solid", "var(--cp-border)"), "&:last-child": { borderBottomStyle: "none" } },
});
